version: '3.8'
services:
  php-apache-container:
    container_name: php-apache
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db-container
    image: php:8.2-apache
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor
    ports:
      - 8000:80

  db-container:
    container_name: pg-db
    image: postgres
    restart: always
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: passwdApi

  adminer-container:
    image: adminer
    restart: always
    ports:
      - 8080:8080
